version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: rq
    versions:
    - 1.8.0
  - dependency-name: gunicorn
    versions:
    - 20.1.0
  - dependency-name: peewee
    versions:
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: cryptography
    versions:
    - 3.4.6
  - dependency-name: rivr
    versions:
    - 0.9.0
