FORMAT: 1A
HOST: https://api.palaverapp.com/

# Palaver

# Group Devices

## Devices [/1/devices]

### Register a new device [POST]

+ Request (application/json)

        { "device_token": "255b34ece6bf163b24474359bc74582ddf2c6726" }

+ Response 201 (application/json)

        {
            "device_token": "255b34ece6bf163b24474359bc74582ddf2c6726",
            "push_token": "83437b46a8f38a444092d81b0d1779d86cc8ea23"
        }

## Notifications [/1/push]

### Send a new notification [POST]

+ Request (application/json)

    + Headers

            Authorization: token 83437b46a8f38a444092d81b0d1779d86cc8ea23

    + Body

            {
                "message": "Hello world!",
                "sender": "kylef",
                "channel": "#palaver",
                "badge": 1
            }

+ Response 204
