FORMAT: 1A
HOST: https://api.palaverapp.com/

# Palaver

# Group Devices

## Devices [/1/devices]

### Register a new device [POST]

+ Request (application/json)
    + Attributes
        + `device_token`: 255b34ece6bf163b24474359bc74582ddf2c6726 (required)

+ Response 201 (application/json)
    + Attributes
        + `device_token`: 255b34ece6bf163b24474359bc74582ddf2c6726 (required)
        + `push_token`: 83437b46a8f38a444092d81b0d1779d86cc8ea23

## Notifications [/1/push]

### Send a new notification [POST]

+ Request (application/json)

    + Headers

            Authorization: token 83437b46a8f38a444092d81b0d1779d86cc8ea23

    + Attributes
        + One Of
            + message: `Hello World!`
            + private: true (fixed)
        + sender: kylef
        + channel: `#palaver`
        + badge: 1 (number)
        + intent (enum)
            + ACTION

+ Response 202

## Device [/device]

### Update a Device [PATCH]

+ Request (application/json)
    + Attributes
        + `apns_token`

+ Response 204

### Delete the Device [DELETE]

+ Request
    + Headers

            Authorization: token 255b34ece6bf163b24474359bc74582ddf2c6726

+ Response 204

## Authorisations [/authorisations]

### List all authorisations [GET]

+ Response 200 (application/json)
    + Attributes (array[Authorisation], fixed-type)

### Create new authorisation [POST]

+ Attributes
    + token
    + scopes

+ Request
    + Headers

            Authorization: token 255b34ece6bf163b24474359bc74582ddf2c6726

+ Response 201 (application/json)
    + Attributes (Authorisation)
        + token: d73e2636cca9e25cf636cca9e

## Authorisation [/authorisations/{id}]

+ Parameters
    + id: 636cca9e

### View an authorisation [GET]

+ Response 200 (application/json)
    + Attributes (Authorisation)

### Delete an authorisation [DELETE]

+ Response 204

## Data Structures

### Scope (enum)

+ all
+ push

### Authorisation

+ url: `/authorisations/636cca9e`
+ scopes (array[Scope], fixed-type)
+ `token_last_eight`: 636cca9e
