version: 2

jobs:
  test:
    working_directory: ~/api.palaverapp.com
    docker:
      - image: circleci/python:2.7.15
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: invoke syncdb
      - run:
          command: python -m unittest discover

workflows:
  version: 2

  test:
    jobs:
      - test
