version: 2

jobs:
  test:
    working_directory: ~/api.palaverapp.com
    docker:
      - image: circleci/python:3.9.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          command: pipenv run invoke syncdb
      - run:
          command: pipenv run pytest

workflows:
  version: 2

  test:
    jobs:
      - test
