on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 2.7.18
      - run: python -m pip install pipenv
      - run: pipenv install
      - run: pipenv run invoke syncdb
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost
      - run: pipenv run python -m unittest discover
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost
